### ISSUE TITLE
Wrong recipient, payload audience != requiredAudience

### ISSUE THREAD

**Issue by skryshtafovych** [actions-on-google/dialogflow-google-sign-in-nodejs#2]
Been trying to figure out what is wrong in my code since Tut does not follow newest changes in UI. Now i am running into Issue Below pleases suggest workaround. Also Which Client ID should i Use since doc not in Sync.

This error seems to occur after "Privacy Policy MSG" is displayed 

```
Error: Wrong recipient, payload audience != requiredAudience
    at OAuth2Client.verifySignedJwtWithCerts (/srv/node_modules/google-auth-library/build/src/auth/oauth2client.js:696:23)
    at OAuth2Client.<anonymous> (/srv/node_modules/google-auth-library/build/src/auth/oauth2client.js:514:38)
    at step (/srv/node_modules/google-auth-library/build/src/auth/oauth2client.js:57:23)
    at Object.next (/srv/node_modules/google-auth-library/build/src/auth/oauth2client.js:38:53)
    at fulfilled (/srv/node_modules/google-auth-library/build/src/auth/oauth2client.js:29:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

```

**Comment by MaltesBytes** [comment]
Same issue here

**Comment by ghost** [comment]
Found any solution ?

**Comment by aaron-cardenas** [comment]
The problem here is the client_id that is being used to create an OAuth2Client and the client_id being used as the audience in the verifyIdToken is not the same. The client_id for the audience should be the client_id that was used in your frontend application to get the id_token.
